// nexus setup — interactive gateway config wizard.
// Prompts for base URL, API key, model; writes .env-gateway with mode 600.
// Non-interactive: `nexus setup --base=URL --key=KEY --model=NAME --yes`
// Zero deps. Node >= 22 ESM.

import { writeFileSync, existsSync, chmodSync, statSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { join } from 'node:path';

const DEFAULT_BASE = 'https://api.asynx6.tech/v1';
const DEFAULT_MODEL = 'hermes-agent';

/** Parse nexus setup argv. */
export function parseSetupArgs(argv) {
  const flags = {};
  const positional = [];
  for (const a of argv) {
    if (a.startsWith('--')) {
      const [k, ...rest] = a.slice(2).split('=');
      flags[k] = rest.length ? rest.join('=') : true;
    } else positional.push(a);
  }
  return { flags, positional };
}

/**
 * Prompt one line. Loop until non-empty when a default is absent.
 * Reads through a line queue so piped stdin (all lines at once, then EOF)
 * still answers every prompt correctly.
 */
function makePrompter(rl) {
  const queue = [];
  let done = false;
  let notify = null;
  rl.on('line', (l) => { queue.push(l); if (notify) { notify(); notify = null; } });
  rl.on('close', () => { done = true; if (notify) { notify(); notify = null; } });
  return async function ask(q, def, emptyOk = false) {
    const suffix = def ? ` [${def}]` : '';
    for (;;) {
      if (!queue.length) {
        if (!done) await new Promise((resolve) => { notify = resolve; });
        if (!queue.length) {
          // closed and nothing buffered
          if (def || emptyOk) return def ?? '';
          throw new Error(`nexus setup: input ended before '${q}' was answered`);
        }
      }
      const line = queue.shift();
      const v = line.trim();
      if (v) return v;
      if (def || emptyOk) return def ?? '';
      // required and empty — ask again
    }
  };
}

/** Build .env-gateway content. */
export function buildEnvFile({ baseUrl, apiKey, models }) {
  return [
    '# NEXUS gateway config — generated by `nexus setup`',
    '# Secrets only. Behavioral settings live in config, not here.',
    `NEXUS_GATEWAY_BASE=${baseUrl}`,
    `NEXUS_GATEWAY_KEY=${apiKey}`,
    `NEXUS_GATEWAY_MODELS=${models}`,
    ''
  ].join('\n');
}

/**
 * Run the setup wizard.
 * @returns {number} exit code (0 ok, 2 bad input)
 */
export async function runSetup(argv, opts = {}) {
  const { flags } = parseSetupArgs(argv);
  const out = opts.stdout ?? console.log;
  const err = opts.stderr ?? console.error;
  const cwd = opts.cwd ?? process.cwd();
  const envPath = opts.envPath ?? join(cwd, '.env-gateway');

  if (existsSync(envPath) && !flags.force && !flags.f) {
    out(`found existing config: ${envPath}`);
    out('run with --force to overwrite, or edit the file directly.');
  }

  // Non-interactive mode: all three from flags.
  const nonInteractive = flags.yes || flags.y;
  let baseUrl = flags.base ?? flags['base-url'];
  let apiKey = flags.key ?? flags.apikey ?? flags['api-key'];
  let models = flags.model ?? flags.models;

  if (nonInteractive) {
    baseUrl = baseUrl ?? DEFAULT_BASE;
    apiKey = apiKey ?? '';
    models = models ?? DEFAULT_MODEL;
    if (!apiKey) {
      err('nexus setup: --key is required in non-interactive mode');
      return 2;
    }
  } else {
    out('nexus setup — configure your AI gateway');
    out('(press Enter to accept the value in brackets)');
    out('');
    // readline needs a stream for output; CLI passes console.log (a function)
    const stdoutArg = typeof out === 'function' ? process.stdout : out;
    const rl = createInterface({ input: opts.stdin ?? process.stdin, output: stdoutArg });
    const say = typeof out === 'function' ? out : (m) => out.write(`${m}\n`);
    const ask = makePrompter(rl);
    let askErr = null;
    try {
      baseUrl = await ask('Gateway base URL', baseUrl ?? DEFAULT_BASE);
      apiKey = await ask('API key', apiKey);
      models = await ask('Model (comma-separated for fallback)', models ?? DEFAULT_MODEL, true);
    } catch (e) { askErr = e; }
    rl.close();
    if (askErr) { err(String(askErr.message || askErr)); return 1; }
    say('');
  }

  if (!baseUrl || !apiKey) {
    err('nexus setup: base URL and API key are required');
    return 2;
  }

  const content = buildEnvFile({ baseUrl, apiKey, models });
  writeFileSync(envPath, content, { mode: 0o600 });

  // Best-effort chmod on POSIX; no-op on Windows.
  try {
    if (process.platform !== 'win32') chmodSync(envPath, 0o600);
  } catch { /* best-effort */ }

  const mode = (() => { try { return statSync(envPath).mode; } catch { return 0; } })();
  out(`Wrote ${envPath} (mode ${mode.toString(8)})`);
  out(`  base   = ${baseUrl}`);
  out(`  model  = ${models}`);
  out('Run `nexus doctor` to verify the connection.');
  return 0;
}
